"""Output formatters for daily narratives."""

import json
from datetime import datetime
from pathlib import Path
from typing import Optional

from loguru import logger

from src.storage.models import DailyNarrative, MarketSnapshot


class MarkdownFormatter:
    """Formats DailyNarrative as research note-style markdown."""

    def format(self, narrative: DailyNarrative, market_snapshot: Optional[MarketSnapshot] = None) -> str:
        """
        Format narrative as markdown research note.

        Args:
            narrative: The daily narrative to format
            market_snapshot: Optional market snapshot for data table

        Returns:
            Formatted markdown string
        """
        lines = []

        # Header
        lines.append(f"# {narrative.headline}")
        lines.append("")
        lines.append(f"**Date:** {narrative.date.strftime('%Y-%m-%d')}")
        lines.append(f"**Confidence Score:** {narrative.confidence_score:.0%}")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Executive Summary
        lines.append("## Executive Summary")
        lines.append("")
        # Take first paragraph of primary narrative as summary
        first_para = narrative.primary_narrative.split("\n\n")[0] if narrative.primary_narrative else ""
        lines.append(first_para)
        lines.append("")

        # Market Data Table (Phase 1)
        if market_snapshot:
            lines.append("## Market Overview")
            lines.append("")
            lines.extend(self._format_market_table(market_snapshot))
            lines.append("")

        # Detailed Analysis
        lines.append("## Detailed Analysis")
        lines.append("")
        lines.append(narrative.primary_narrative)
        lines.append("")

        # Supporting Points
        if narrative.supporting_narratives:
            lines.append("## Key Supporting Evidence")
            lines.append("")
            for point in narrative.supporting_narratives:
                lines.append(f"- {point}")
            lines.append("")

        # Key Moves
        if narrative.key_moves_explained:
            lines.append("## Individual Asset Analysis")
            lines.append("")
            for move in narrative.key_moves_explained:
                symbol = move.get("symbol", "Unknown")
                explanation = move.get("explanation", "")
                lines.append(f"**{symbol}:** {explanation}")
                lines.append("")

        # Prediction Market Insights
        if narrative.prediction_market_insights:
            lines.append("## Prediction Market Signals")
            lines.append("")
            for insight in narrative.prediction_market_insights:
                if isinstance(insight, dict):
                    insight_text = insight.get("insight", str(insight))
                else:
                    insight_text = str(insight)
                lines.append(f"- {insight_text}")
            lines.append("")

        # Unexplained Moves
        if narrative.unexplained_moves:
            lines.append("## Unexplained Movements")
            lines.append("")
            for move in narrative.unexplained_moves:
                lines.append(f"- {move}")
            lines.append("")

        # Looking Ahead
        if narrative.looking_ahead:
            lines.append("## Looking Ahead")
            lines.append("")
            lines.append(narrative.looking_ahead)
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("## Methodology")
        lines.append("")
        lines.append("**Data Sources:**")
        for source in narrative.data_sources:
            lines.append(f"- {source}")
        lines.append("")

        if narrative.metadata:
            lines.append("**Analysis Details:**")
            tools_used = narrative.metadata.get("tools_used", [])
            num_hypotheses = narrative.metadata.get("num_hypotheses", 0)
            num_investigations = narrative.metadata.get("num_investigations", 0)

            lines.append(f"- Hypotheses generated: {num_hypotheses}")
            lines.append(f"- Hypotheses investigated: {num_investigations}")
            lines.append(f"- Tools used: {len(tools_used)}")
            lines.append("")

        lines.append(f"*Generated by Market Narrative Agent on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")

        return "\n".join(lines)

    def _format_market_table(self, snapshot) -> list[str]:
        """Format market snapshot as markdown table.

        Args:
            snapshot: Market snapshot data (MarketSnapshot object or dict)

        Returns:
            List of markdown table lines
        """
        lines = []

        # Helper to access both dict and object attributes
        is_dict = isinstance(snapshot, dict)

        def get_field(field_name):
            return snapshot.get(field_name) if is_dict else getattr(snapshot, field_name, None)

        # Major Indices Table
        major_indices = get_field("major_indices")
        if major_indices:
            lines.append("### Major Indices")
            lines.append("")
            lines.append("| Index | Change |")
            lines.append("|-------|--------|")
            for symbol, change in major_indices.items():
                lines.append(f"| {symbol} | {change:+.2f}% |")
            lines.append("")

        # Sector Performance Table
        sector_performance = get_field("sector_performance")
        if sector_performance:
            lines.append("### Sector Performance")
            lines.append("")
            lines.append("| Sector | Change |")
            lines.append("|--------|--------|")
            # Sort sectors by performance
            sorted_sectors = sorted(sector_performance.items(), key=lambda x: x[1], reverse=True)
            for sector, change in sorted_sectors:
                lines.append(f"| {sector} | {change:+.2f}% |")
            lines.append("")

        # Top Movers
        biggest_gainers = get_field("biggest_gainers") or []
        biggest_losers = get_field("biggest_losers") or []

        if biggest_gainers or biggest_losers:
            lines.append("### Top Movers")
            lines.append("")
            lines.append("| Symbol | Name | Change | Volume Ratio |")
            lines.append("|--------|------|--------|--------------|")

            # Top 5 gainers
            for mover in biggest_gainers[:5]:
                # Handle both dict and object
                if isinstance(mover, dict):
                    symbol = mover.get("symbol", "")
                    name = mover.get("name", symbol)
                    change_pct = mover.get("change_percent", 0)
                    vol_ratio = mover.get("volume_ratio")
                else:
                    symbol = mover.symbol
                    name = mover.name or symbol
                    change_pct = mover.change_percent
                    vol_ratio = mover.volume_ratio

                vol_str = f"{vol_ratio:.2f}x" if vol_ratio else "N/A"
                lines.append(f"| {symbol} | {name} | {change_pct:+.2f}% | {vol_str} |")

            # Top 5 losers
            for mover in biggest_losers[:5]:
                # Handle both dict and object
                if isinstance(mover, dict):
                    symbol = mover.get("symbol", "")
                    name = mover.get("name", symbol)
                    change_pct = mover.get("change_percent", 0)
                    vol_ratio = mover.get("volume_ratio")
                else:
                    symbol = mover.symbol
                    name = mover.name or symbol
                    change_pct = mover.change_percent
                    vol_ratio = mover.volume_ratio

                vol_str = f"{vol_ratio:.2f}x" if vol_ratio else "N/A"
                lines.append(f"| {symbol} | {name} | {change_pct:+.2f}% | {vol_str} |")
            lines.append("")

        # Market Breadth
        market_breadth = get_field("market_breadth")
        if market_breadth:
            lines.append("### Market Breadth")
            lines.append("")
            # market_breadth is always a dict
            advancers = market_breadth.get("advancers", 0)
            decliners = market_breadth.get("decliners", 0)
            unchanged = market_breadth.get("unchanged", 0)
            lines.append(f"- **Advancers:** {advancers}")
            lines.append(f"- **Decliners:** {decliners}")
            lines.append(f"- **Unchanged:** {unchanged}")
            lines.append("")

        # Volatility
        volatility = get_field("volatility")
        if volatility:
            lines.append("### Volatility")
            lines.append("")
            for symbol, value in volatility.items():
                lines.append(f"- **{symbol}:** {value:.2f}")
            lines.append("")

        return lines


class OutputWriter:
    """Handles writing outputs to files."""

    def __init__(self, output_dir: Path):
        """
        Initialize output writer.

        Args:
            output_dir: Base output directory (e.g., ./outputs)
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def save_narrative(
        self,
        narrative: DailyNarrative,
        market_snapshot: Optional[MarketSnapshot] = None,
        logs: Optional[str] = None,
    ) -> dict[str, Path]:
        """
        Save narrative to files (markdown, JSON, logs).

        Args:
            narrative: The daily narrative to save
            market_snapshot: Optional market snapshot for markdown table
            logs: Optional log content to save

        Returns:
            Dict mapping output type to file path
        """
        # Create date-specific directory
        date_str = narrative.date.strftime("%Y-%m-%d")
        date_dir = self.output_dir / date_str
        date_dir.mkdir(parents=True, exist_ok=True)

        logger.info(f"Saving outputs to {date_dir}")

        output_files = {}

        # Save markdown
        markdown_path = date_dir / "narrative.md"
        formatter = MarkdownFormatter()
        markdown_content = formatter.format(narrative, market_snapshot)
        markdown_path.write_text(markdown_content, encoding="utf-8")
        output_files["markdown"] = markdown_path
        logger.info(f"Saved markdown to {markdown_path}")

        # Save JSON
        json_path = date_dir / "narrative.json"
        json_content = narrative.model_dump_json(indent=2)
        json_path.write_text(json_content, encoding="utf-8")
        output_files["json"] = json_path
        logger.info(f"Saved JSON to {json_path}")

        # Save market snapshot (if provided)
        if market_snapshot:
            snapshot_path = date_dir / "market_snapshot.json"
            # Handle both Pydantic models and dicts
            if isinstance(market_snapshot, dict):
                snapshot_content = json.dumps(market_snapshot, indent=2, default=str)
            else:
                snapshot_content = market_snapshot.model_dump_json(indent=2)
            snapshot_path.write_text(snapshot_content, encoding="utf-8")
            output_files["market_snapshot"] = snapshot_path
            logger.info(f"Saved market snapshot to {snapshot_path}")

        # Save logs (if provided)
        if logs:
            logs_path = date_dir / "agent_logs.txt"
            logs_path.write_text(logs, encoding="utf-8")
            output_files["logs"] = logs_path
            logger.info(f"Saved logs to {logs_path}")

        return output_files

    def save_raw_data(
        self, date: datetime, data_type: str, data: dict, filename: Optional[str] = None
    ) -> Path:
        """
        Save raw data (e.g., headlines, predictions) to JSON file.

        Args:
            date: Date for the data
            data_type: Type of data (e.g., 'headlines', 'predictions')
            data: Data to save
            filename: Optional custom filename (defaults to {data_type}.json)

        Returns:
            Path to saved file
        """
        date_str = date.strftime("%Y-%m-%d")
        date_dir = self.output_dir / date_str
        date_dir.mkdir(parents=True, exist_ok=True)

        filename = filename or f"{data_type}.json"
        file_path = date_dir / filename

        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, default=str)

        logger.info(f"Saved {data_type} to {file_path}")
        return file_path
